name: youtube-stats actions ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps: 
    - uses: actions/checkout@v2
      name: Check out code
      
    - name: Use Node.js
      uses: actions/setup-node@v2
        
    - run: npm install
    - run: npm run build --if-present
      
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: hyiik09/assignment3
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
